name: Rust Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-skyline
      run: cargo install --git https://github.com/jam1garner/cargo-skyline
    - name: Install rust-std-skyline-squashed
      run: cd .. && git clone https://github.com/jam1garner/rust-std-skyline-squashed && cd -
    - name: Attempt to build
      run: PATH=$PATH:/usr/share/rust/.rustup/toolchains/nightly-2020-04-10-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin cargo skyline build --release
    - name: Create a Release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: master
        # The name of the release. For example, `Release v1.0.1`
        release_name: master
        # Text describing the contents of the tag.
        body: Build of skyline-rs-template from master.
        # `true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`
        draft: false
        # `true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`
        prerelease: true    

# uncomment the build step below to build on every change to master.

#     - name: Upload Release
#       uses: majkrzak/create-release@latest
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}
#         name: master
#         code: master
#         body: Build of skyline-rs-template from master.
#         prerelease: true
#         recreate: true
#         assets: ./target/aarch64-skyline-switch/release/libskyline_rs_template.nro:libskyline_rs_template.nro:application/octet-stream
  

